services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker_data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: happyreturns_user
      MONGO_INITDB_ROOT_PASSWORD: happyreturns_pass